import Head from "next/head";
import Favorites from "../components/Favorites";

export default function Home() {
  return (
    <>
      <Head>
        <title>NotARealStore</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="bg-white">
        <Favorites />
      </main>
    </>
  );
}
